functionsDirectory = "/Users/michaelcasper/Downloads/backend_system/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []

[build]
publish = "/Users/michaelcasper/Downloads/backend_system"
publishOrigin = "config"
functions = "/Users/michaelcasper/Downloads/backend_system/netlify/functions"

[build.environment]
NODE_VERSION = "18.20.3"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
included_files = ["netlify/functions/**/*.js"]
external_node_modules = ["stripe", "@supabase/supabase-js"]
node_bundler = "esbuild"

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/login"
to = "/login.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/signup"
to = "/signup.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/subscribe"
to = "/subscribe.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/success"
to = "/success.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/cancel"
to = "/cancel.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/dashboard"
to = "/dashboard.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/standard"
to = "/standard.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/sim_cards"
to = "/sim_cards.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/xg_stats"
to = "/xg_stats.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/value_stats"
to = "/value_stats.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/outlooks"
to = "/outlooks.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/player_simulations"
to = "/player_simulations.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]